spring:

  datasource:
    url: jdbc:mariadb://inspien-assignment.cumvd7l8ejzn.ap-northeast-2.rds.amazonaws.com:3306/assignment01
    driver-class-name: org.mariadb.jdbc.Driver
    username: jongmin
    password: qkrwhdals1!

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: usergroup
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
